import { ItemDef } from './types';

export const BLOCKS = {
  AIR: 0,
  GRASS: 1,
  DIRT: 2,
  STONE: 3,
  COBBLESTONE: 4,
  WOOD: 5,
  LEAVES: 6,
  PLANKS: 7,
  SAND: 8,
  GLASS: 9,
  BRICK: 10,
  BOOKSHELF: 11,
  COAL_ORE: 12,
  IRON_ORE: 13,
  GOLD_ORE: 14,
  DIAMOND_ORE: 15,
  CRAFTING_TABLE: 16,
  FURNACE: 17,
  CHEST: 18,
  TNT: 19,
  BED: 20,
  TORCH: 21,
  REDSTONE: 22,
  FLOWER: 23,
  WATER: 24,
  BEDROCK: 25,
} as const;

export type BlockId = typeof BLOCKS[keyof typeof BLOCKS];

export interface BlockProperty {
  id: BlockId;
  name: string;
  itemId: string;
  hardness: number; // Break duration in seconds with bare hands
  sound: 'grass' | 'stone' | 'wood' | 'sand';
  preferredTool?: 'pickaxe' | 'axe' | 'shovel';
  minTier?: number; // 0: none, 1: wood, 2: stone, 3: iron, 4: diamond
  drops: { itemId: string; count: number; chance?: number }[];
  isSolid: boolean;
  isTransparent?: boolean;
  isLightSource?: boolean;
  isInteractive?: 'crafting_table' | 'furnace' | 'chest' | 'bed' | 'tnt';
}

export const BLOCK_DEFS: Record<number, BlockProperty> = {
  [BLOCKS.GRASS]: {
    id: BLOCKS.GRASS,
    name: '草ブロック',
    itemId: 'grass',
    hardness: 0.6,
    sound: 'grass',
    preferredTool: 'shovel',
    drops: [{ itemId: 'dirt', count: 1 }],
    isSolid: true,
  },
  [BLOCKS.DIRT]: {
    id: BLOCKS.DIRT,
    name: '土',
    itemId: 'dirt',
    hardness: 0.5,
    sound: 'grass',
    preferredTool: 'shovel',
    drops: [{ itemId: 'dirt', count: 1 }],
    isSolid: true,
  },
  [BLOCKS.STONE]: {
    id: BLOCKS.STONE,
    name: '石',
    itemId: 'stone',
    hardness: 1.6,
    sound: 'stone',
    preferredTool: 'pickaxe',
    minTier: 1, // Wooden pickaxe drops cobblestone, bare hands drops nothing
    drops: [{ itemId: 'cobblestone', count: 1 }],
    isSolid: true,
  },
  [BLOCKS.COBBLESTONE]: {
    id: BLOCKS.COBBLESTONE,
    name: '丸石',
    itemId: 'cobblestone',
    hardness: 1.5,
    sound: 'stone',
    preferredTool: 'pickaxe',
    minTier: 1,
    drops: [{ itemId: 'cobblestone', count: 1 }],
    isSolid: true,
  },
  [BLOCKS.WOOD]: {
    id: BLOCKS.WOOD,
    name: '原木',
    itemId: 'wood',
    hardness: 1.2,
    sound: 'wood',
    preferredTool: 'axe',
    drops: [{ itemId: 'wood', count: 1 }],
    isSolid: true,
  },
  [BLOCKS.LEAVES]: {
    id: BLOCKS.LEAVES,
    name: '木の葉',
    itemId: 'leaves',
    hardness: 0.2,
    sound: 'grass',
    drops: [
      { itemId: 'stick', count: 1, chance: 0.35 },
      { itemId: 'apple', count: 1, chance: 0.15 },
    ],
    isSolid: true,
  },
  [BLOCKS.PLANKS]: {
    id: BLOCKS.PLANKS,
    name: '木材',
    itemId: 'planks',
    hardness: 1.0,
    sound: 'wood',
    preferredTool: 'axe',
    drops: [{ itemId: 'planks', count: 1 }],
    isSolid: true,
  },
  [BLOCKS.SAND]: {
    id: BLOCKS.SAND,
    name: '砂',
    itemId: 'sand',
    hardness: 0.5,
    sound: 'sand',
    preferredTool: 'shovel',
    drops: [{ itemId: 'sand', count: 1 }],
    isSolid: true,
  },
  [BLOCKS.GLASS]: {
    id: BLOCKS.GLASS,
    name: 'ガラス',
    itemId: 'glass',
    hardness: 0.3,
    sound: 'stone',
    drops: [],
    isSolid: true,
    isTransparent: true,
  },
  [BLOCKS.BRICK]: {
    id: BLOCKS.BRICK,
    name: 'レンガ',
    itemId: 'brick',
    hardness: 1.8,
    sound: 'stone',
    preferredTool: 'pickaxe',
    minTier: 1,
    drops: [{ itemId: 'brick', count: 1 }],
    isSolid: true,
  },
  [BLOCKS.BOOKSHELF]: {
    id: BLOCKS.BOOKSHELF,
    name: '本棚',
    itemId: 'bookshelf',
    hardness: 1.2,
    sound: 'wood',
    preferredTool: 'axe',
    drops: [{ itemId: 'planks', count: 3 }],
    isSolid: true,
  },
  [BLOCKS.COAL_ORE]: {
    id: BLOCKS.COAL_ORE,
    name: '石炭鉱石',
    itemId: 'coal_ore',
    hardness: 2.2,
    sound: 'stone',
    preferredTool: 'pickaxe',
    minTier: 1,
    drops: [{ itemId: 'coal', count: 1 }],
    isSolid: true,
  },
  [BLOCKS.IRON_ORE]: {
    id: BLOCKS.IRON_ORE,
    name: '鉄鉱石',
    itemId: 'iron_ore',
    hardness: 2.8,
    sound: 'stone',
    preferredTool: 'pickaxe',
    minTier: 2, // Stone pickaxe or better
    drops: [{ itemId: 'iron_ore', count: 1 }],
    isSolid: true,
  },
  [BLOCKS.GOLD_ORE]: {
    id: BLOCKS.GOLD_ORE,
    name: '金鉱石',
    itemId: 'gold_ore',
    hardness: 3.0,
    sound: 'stone',
    preferredTool: 'pickaxe',
    minTier: 3, // Iron pickaxe or better
    drops: [{ itemId: 'gold_ore', count: 1 }],
    isSolid: true,
  },
  [BLOCKS.DIAMOND_ORE]: {
    id: BLOCKS.DIAMOND_ORE,
    name: 'ダイヤ鉱石',
    itemId: 'diamond_ore',
    hardness: 3.5,
    sound: 'stone',
    preferredTool: 'pickaxe',
    minTier: 3, // Iron pickaxe or better
    drops: [{ itemId: 'diamond', count: 1 }],
    isSolid: true,
  },
  [BLOCKS.CRAFTING_TABLE]: {
    id: BLOCKS.CRAFTING_TABLE,
    name: '作業台',
    itemId: 'crafting_table',
    hardness: 1.2,
    sound: 'wood',
    preferredTool: 'axe',
    drops: [{ itemId: 'crafting_table', count: 1 }],
    isSolid: true,
    isInteractive: 'crafting_table',
  },
  [BLOCKS.FURNACE]: {
    id: BLOCKS.FURNACE,
    name: 'かまど',
    itemId: 'furnace',
    hardness: 2.0,
    sound: 'stone',
    preferredTool: 'pickaxe',
    minTier: 1,
    drops: [{ itemId: 'furnace', count: 1 }],
    isSolid: true,
    isInteractive: 'furnace',
  },
  [BLOCKS.CHEST]: {
    id: BLOCKS.CHEST,
    name: 'チェスト',
    itemId: 'chest',
    hardness: 1.4,
    sound: 'wood',
    preferredTool: 'axe',
    drops: [{ itemId: 'chest', count: 1 }],
    isSolid: true,
    isInteractive: 'chest',
  },
  [BLOCKS.TNT]: {
    id: BLOCKS.TNT,
    name: 'TNT',
    itemId: 'tnt',
    hardness: 0.1,
    sound: 'grass',
    drops: [{ itemId: 'tnt', count: 1 }],
    isSolid: true,
    isInteractive: 'tnt',
  },
  [BLOCKS.BED]: {
    id: BLOCKS.BED,
    name: 'ベッド',
    itemId: 'bed',
    hardness: 0.8,
    sound: 'wood',
    drops: [{ itemId: 'bed', count: 1 }],
    isSolid: true,
    isInteractive: 'bed',
  },
  [BLOCKS.TORCH]: {
    id: BLOCKS.TORCH,
    name: '松明',
    itemId: 'torch',
    hardness: 0.05,
    sound: 'wood',
    drops: [{ itemId: 'torch', count: 1 }],
    isSolid: false,
    isLightSource: true,
  },
  [BLOCKS.REDSTONE]: {
    id: BLOCKS.REDSTONE,
    name: '回路',
    itemId: 'redstone',
    hardness: 0.5,
    sound: 'stone',
    drops: [{ itemId: 'redstone', count: 1 }],
    isSolid: true,
    isLightSource: true,
  },
  [BLOCKS.FLOWER]: {
    id: BLOCKS.FLOWER,
    name: '花',
    itemId: 'flower',
    hardness: 0.05,
    sound: 'grass',
    drops: [{ itemId: 'flower', count: 1 }],
    isSolid: false,
  },
  [BLOCKS.WATER]: {
    id: BLOCKS.WATER,
    name: '水',
    itemId: 'water',
    hardness: 100, // Unbreakable
    sound: 'grass',
    drops: [],
    isSolid: false,
    isTransparent: true,
  },
  [BLOCKS.BEDROCK]: {
    id: BLOCKS.BEDROCK,
    name: '岩盤',
    itemId: 'bedrock',
    hardness: 999999, // Unbreakable
    sound: 'stone',
    drops: [],
    isSolid: true,
  },
};

export const ITEMS: Record<string, ItemDef> = {
  // Blocks
  grass: { id: 'grass', name: '草ブロック', isBlock: true, blockType: BLOCKS.GRASS, maxStack: 64, textureId: 'grass_side' },
  dirt: { id: 'dirt', name: '土', isBlock: true, blockType: BLOCKS.DIRT, maxStack: 64, textureId: 'dirt' },
  stone: { id: 'stone', name: '石', isBlock: true, blockType: BLOCKS.STONE, maxStack: 64, textureId: 'stone' },
  cobblestone: { id: 'cobblestone', name: '丸石', isBlock: true, blockType: BLOCKS.COBBLESTONE, maxStack: 64, textureId: 'cobblestone' },
  wood: { id: 'wood', name: '原木', isBlock: true, blockType: BLOCKS.WOOD, maxStack: 64, textureId: 'wood_side' },
  leaves: { id: 'leaves', name: '木の葉', isBlock: true, blockType: BLOCKS.LEAVES, maxStack: 64, textureId: 'leaves' },
  planks: { id: 'planks', name: '木材', isBlock: true, blockType: BLOCKS.PLANKS, maxStack: 64, textureId: 'planks' },
  sand: { id: 'sand', name: '砂', isBlock: true, blockType: BLOCKS.SAND, maxStack: 64, textureId: 'sand' },
  glass: { id: 'glass', name: 'ガラス', isBlock: true, blockType: BLOCKS.GLASS, maxStack: 64, textureId: 'glass' },
  brick: { id: 'brick', name: 'レンガ', isBlock: true, blockType: BLOCKS.BRICK, maxStack: 64, textureId: 'brick' },
  bookshelf: { id: 'bookshelf', name: '本棚', isBlock: true, blockType: BLOCKS.BOOKSHELF, maxStack: 64, textureId: 'bookshelf' },
  coal_ore: { id: 'coal_ore', name: '石炭鉱石', isBlock: true, blockType: BLOCKS.COAL_ORE, maxStack: 64, textureId: 'coal_ore' },
  iron_ore: { id: 'iron_ore', name: '鉄鉱石', isBlock: true, blockType: BLOCKS.IRON_ORE, maxStack: 64, textureId: 'iron_ore' },
  gold_ore: { id: 'gold_ore', name: '金鉱石', isBlock: true, blockType: BLOCKS.GOLD_ORE, maxStack: 64, textureId: 'gold_ore' },
  diamond_ore: { id: 'diamond_ore', name: 'ダイヤ鉱石', isBlock: true, blockType: BLOCKS.DIAMOND_ORE, maxStack: 64, textureId: 'diamond_ore' },
  crafting_table: { id: 'crafting_table', name: '作業台', isBlock: true, blockType: BLOCKS.CRAFTING_TABLE, maxStack: 64, textureId: 'crafting_table_top', description: '右クリックで3x3クラフト' },
  furnace: { id: 'furnace', name: 'かまど', isBlock: true, blockType: BLOCKS.FURNACE, maxStack: 64, textureId: 'furnace_front', description: '鉱石の精錬や肉の調理' },
  chest: { id: 'chest', name: 'チェスト', isBlock: true, blockType: BLOCKS.CHEST, maxStack: 64, textureId: 'chest_front', description: 'アイテムの大容量保管' },
  tnt: { id: 'tnt', name: 'TNT', isBlock: true, blockType: BLOCKS.TNT, maxStack: 64, textureId: 'tnt_side', description: '攻撃すると着火して大爆発！' },
  bed: { id: 'bed', name: 'ベッド', isBlock: true, blockType: BLOCKS.BED, maxStack: 1, textureId: 'bed', description: '夜に寝ると朝になりHP全快' },
  torch: { id: 'torch', name: '松明', isBlock: true, blockType: BLOCKS.TORCH, maxStack: 64, textureId: 'torch', description: '周囲を明るく照らす' },
  redstone: { id: 'redstone', name: '回路', isBlock: true, blockType: BLOCKS.REDSTONE, maxStack: 64, textureId: 'redstone' },
  flower: { id: 'flower', name: '花', isBlock: true, blockType: BLOCKS.FLOWER, maxStack: 64, textureId: 'flower' },

  // Raw Materials
  stick: { id: 'stick', name: '棒', isBlock: false, maxStack: 64, textureId: 'stick' },
  coal: { id: 'coal', name: '石炭', isBlock: false, maxStack: 64, textureId: 'coal' },
  iron_ingot: { id: 'iron_ingot', name: '鉄インゴット', isBlock: false, maxStack: 64, textureId: 'iron_ingot' },
  gold_ingot: { id: 'gold_ingot', name: '金インゴット', isBlock: false, maxStack: 64, textureId: 'gold_ingot' },
  diamond: { id: 'diamond', name: 'ダイヤモンド', isBlock: false, maxStack: 64, textureId: 'diamond' },

  // Food
  raw_meat: { id: 'raw_meat', name: '生の肉', isBlock: false, maxStack: 64, textureId: 'raw_meat', foodRestore: { health: 1, hunger: 2 }, description: '右クリックで食べる(かまどで調理可能)' },
  cooked_steak: { id: 'cooked_steak', name: 'ステーキ', isBlock: false, maxStack: 64, textureId: 'cooked_steak', foodRestore: { health: 4, hunger: 7 }, description: '右クリックで食べる(大幅回復)' },
  apple: { id: 'apple', name: 'リンゴ', isBlock: false, maxStack: 64, textureId: 'apple', foodRestore: { health: 2, hunger: 3 }, description: '右クリックで食べる' },

  // Tools - Pickaxes
  wood_pickaxe: { id: 'wood_pickaxe', name: '木のツルハシ', isBlock: false, maxStack: 1, textureId: 'wood_pickaxe', toolType: 'pickaxe', toolTier: 1, damage: 2, durability: 60 },
  stone_pickaxe: { id: 'stone_pickaxe', name: '石のツルハシ', isBlock: false, maxStack: 1, textureId: 'stone_pickaxe', toolType: 'pickaxe', toolTier: 2, damage: 3, durability: 130 },
  iron_pickaxe: { id: 'iron_pickaxe', name: '鉄のツルハシ', isBlock: false, maxStack: 1, textureId: 'iron_pickaxe', toolType: 'pickaxe', toolTier: 3, damage: 4, durability: 250 },
  diamond_pickaxe: { id: 'diamond_pickaxe', name: 'ダイヤのツルハシ', isBlock: false, maxStack: 1, textureId: 'diamond_pickaxe', toolType: 'pickaxe', toolTier: 4, damage: 5, durability: 1500 },

  // Tools - Swords
  wood_sword: { id: 'wood_sword', name: '木の剣', isBlock: false, maxStack: 1, textureId: 'wood_sword', toolType: 'sword', toolTier: 1, damage: 4, durability: 60 },
  stone_sword: { id: 'stone_sword', name: '石の剣', isBlock: false, maxStack: 1, textureId: 'stone_sword', toolType: 'sword', toolTier: 2, damage: 5, durability: 130 },
  iron_sword: { id: 'iron_sword', name: '鉄の剣', isBlock: false, maxStack: 1, textureId: 'iron_sword', toolType: 'sword', toolTier: 3, damage: 6, durability: 250 },
  diamond_sword: { id: 'diamond_sword', name: 'ダイヤの剣', isBlock: false, maxStack: 1, textureId: 'diamond_sword', toolType: 'sword', toolTier: 4, damage: 8, durability: 1500 },

  // Tools - Axes & Shovels
  wood_axe: { id: 'wood_axe', name: '木の斧', isBlock: false, maxStack: 1, textureId: 'wood_axe', toolType: 'axe', toolTier: 1, damage: 3, durability: 60 },
  stone_axe: { id: 'stone_axe', name: '石の斧', isBlock: false, maxStack: 1, textureId: 'stone_axe', toolType: 'axe', toolTier: 2, damage: 4, durability: 130 },
  iron_axe: { id: 'iron_axe', name: '鉄の斧', isBlock: false, maxStack: 1, textureId: 'iron_axe', toolType: 'axe', toolTier: 3, damage: 5, durability: 250 },
  wood_shovel: { id: 'wood_shovel', name: '木のシャベル', isBlock: false, maxStack: 1, textureId: 'wood_shovel', toolType: 'shovel', toolTier: 1, damage: 1, durability: 60 },

  // Ranged Weapons
  bow: { id: 'bow', name: '弓', isBlock: false, maxStack: 1, textureId: 'bow', toolType: 'bow', durability: 300, description: '矢を消費して遠距離攻撃' },
  arrow: { id: 'arrow', name: '矢', isBlock: false, maxStack: 64, textureId: 'arrow' },
};
